/* THIS FILE WAS GENERATED BY arch/x86/gen-syscall.bash -- DO NOT EDIT */

#include <stddef.h>
#include <linux/audit.h>
#include <linux/bpf_common.h>
#include <linux/filter.h>
#include <linux/seccomp.h>

/* For the x32 ABI, all system call numbers have bit 30 set */
#define X32_SYSCALL_BIT 0x40000000

const struct sock_filter syscall_filter[] = {
	BPF_STMT(BPF_LD | BPF_W | BPF_ABS, (offsetof(struct seccomp_data, arch))),
	BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, AUDIT_ARCH_I386, 10, 0),
	BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, AUDIT_ARCH_X86_64, 1, 0),
	BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_KILL_PROCESS),
	BPF_STMT(BPF_LD | BPF_W | BPF_ABS, (offsetof(struct seccomp_data, nr))),
	BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, X32_SYSCALL_BIT, 0, 1),
	BPF_STMT(BPF_ALU | BPF_SUB | BPF_K, X32_SYSCALL_BIT),
	BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 133, 0, 1),
	BPF_STMT(BPF_RET + BPF_K, SECCOMP_RET_USER_NOTIF),
	BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 259, 0, 1),
	BPF_STMT(BPF_RET + BPF_K, SECCOMP_RET_USER_NOTIF),
	BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_ALLOW),
	BPF_STMT(BPF_LD | BPF_W | BPF_ABS, (offsetof(struct seccomp_data, nr))),
	BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 14, 0, 1),
	BPF_STMT(BPF_RET + BPF_K, SECCOMP_RET_USER_NOTIF),
	BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 297, 0, 1),
	BPF_STMT(BPF_RET + BPF_K, SECCOMP_RET_USER_NOTIF),
	BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_ALLOW),
};

const size_t syscall_filter_length = sizeof (syscall_filter) / sizeof (struct sock_filter);

/* THIS FILE WAS GENERATED BY arch/x86/gen-syscall.bash -- DO NOT EDIT */
