/* THIS FILE WAS GENERATED BY arch/x86/gen-syscall.bash -- DO NOT EDIT */

extern const struct sock_filter syscall_filter[];
extern const size_t syscall_filter_length;

#define BST_NR_mknod 133
#define BST_NR_mknodat 259
#define BST_NR_lstat64_32 196
#define BST_NR_stat64_32 195
#define BST_NR_fstat64_32 197
#define BST_NR_mknod_32 14
#define BST_NR_statx_32 383
#define BST_NR_fstatat64_32 300
#define BST_NR_mknodat_32 297

#define BST_SECCOMP_32 1

#define BST_NR_MAX 259
#define BST_NR_MAX32 383

/* THIS FILE WAS GENERATED BY arch/x86/gen-syscall.bash -- DO NOT EDIT */
