/* THIS FILE WAS GENERATED BY arch/aarch64/gen-syscall.bash -- DO NOT EDIT */

extern const struct sock_filter syscall_filter[];
extern const size_t syscall_filter_length;

#define BST_NR_mknodat 33

/* THIS FILE WAS GENERATED BY arch/aarch64/gen-syscall.bash -- DO NOT EDIT */
